#!/usr/bin/env python3
from math import pi


COMPONENT_DIAMETER = 10
VACUUM_REFRACTIVE_INDEX = 1
MATERIAL_REFRACTIVE_INDEX = 1.5
RAYS = 21

INITIAL_ANGLE = pi/36
FIRST_INTERFACE = 20
THICKNESS_LENS = 6
# SECOND_INTERFACE = FIRST_INTERFACE + THICKNESS_LENS
DISTANCE_END = 20
# END = SECOND_INTERFACE + DISTANCE_END
