#!/usr/bin/env python3
from math import pi


COMPONENT_DIAMETER = 10
VACUUM_REFRACTIVE_INDEX = 1
MATERIAL_REFRACTIVE_INDEX = 1.5
RAYS = 21
BEAM_DIAMETER = 5
RAYS_RATYRACE = 8
RAYS_SCATTER = 100
ANGLE = pi/6

FIRST_LENS_RADIUS = 10
SECOND_LENS_RADIUS = -10

INITIAL_ANGLE = pi/36
FIRST_INTERFACE = 10
THICKNESS_LENS = 3
# SECOND_INTERFACE = FIRST_INTERFACE + THICKNESS_LENS
DISTANCE_END = 20
# END = SECOND_INTERFACE + DISTANCE_END
