from math import pi


COMPONENT_DIAMETER = 10
VACUUM_REFRACTIVE_INDEX = 1
MATERIAL_REFRACTIVE_INDEX = 1.5
RAYS = 20

INITIAL_ANGLE = pi/36
FIRST_INTERFACE = 20
DISTANCE_SECOND_INTERFACE = 6
SECOND_INTERFACE = FIRST_INTERFACE + DISTANCE_SECOND_INTERFACE
DISTANCE_END = 20
END = SECOND_INTERFACE + DISTANCE_END
